### ISSUE TITLE
Doesn't work on dedicated servers

### ISSUE THREAD

**Issue by NyakoFox** [VioletRoses/WeirdEquipment#1]
This line exists in two items: `MinecraftClient client = MinecraftClient.getInstance();`

Grabbing the client will never work on the dedicated server since none exists.

**Comment by Alkaline-Dreams** [comment]
Thanks for the report! That was a total oversight on my end, will be pushing a fix shortly.

**Comment by Alkaline-Dreams** [comment]
Fix has been pushed, release is out on Github and pending on Curseforge.
